Repository telicent-oss/shared-workflows, pull requests merged in 2024-06, with the labels that each got.

#26 Fix Maven Server configuration
  .github/workflows/maven.yml
Labels: bug

#20 update: Store npm SBOM & docker SBOM & reports
  .github/workflows/docker-push-to-registries.yml
  .github/workflows/trivy-image-scan.yml
  .github/workflows/vulnerability-scanning-on-repo.yml
Labels: QA

#29 Various improvements to Maven Workflow (CORE-291)
  .github/workflows/docker-push-to-registries.yml
  .github/workflows/maven.yml
  README.md
  docs/maven.md
  isMavenCentralReady.sh
Labels: documentation, enhancement

#36 Dependabot skips Image Scans
  .github/workflows/docker-push-to-registries.yml
Labels: bug
